# override name to avoid collision with knative eventing resources
nameOverride:
replicaCount: 1
serviceAccount:
  # name defines optionally another name than the default name for the service account
  name: ""
  annotations: ""


clusterRole:
  # name defines optionally another name than the default name for the cluster role
  name: ""

image:
  # name is the name of the container image for the eventing-controller
  name: "eventing-controller"
  # tag is the container tag of the eventing-controller image
  tag: "PR-10674"
  # pullPolicy is the pullPolicy for the eventing-controller image
  pullPolicy: "IfNotPresent"

podSecurityContext:

bebSecret:
  nameSuffix: "-beb-oauth2"

resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi

metrics:
  service:
    nameSuffix: "-metrics"

healthProbe:
   port: 8081
   scheme: HTTP
   liveness:
     service:
       path: "/healthz"
     failureThreshold: 3
     initialDelaySeconds: 5
     periodSeconds: 10
     successThreshold: 1
     timeoutSeconds: 2
   readiness:
     service:
       path: "/readyz"
     failureThreshold: 3
     initialDelaySeconds: 10
     periodSeconds: 3
     successThreshold: 1
     timeoutSeconds: 2

#TODO(sayanh): Remove this as a part of https://github.com/kyma-project/kyma/issues/10317
clusterRoleBindingSuffix: "-crole-binding"
